research_story_theme_task:
  description: >
    Based on the user input "{story_theme}" and target age group "{age_range}", research the latest topics
    and themes. Use Wikipedia and other sources to gather background information and educational elements. 
    Establish a final theme for a picture book, then determine the key educational elements.
  expected_output: >
    Final theme for a picture book, key educational elements.
develop_story_outline_task:
  description: >
    Create a detailed story outline based on the research findings and user requirements "{story_theme}".
    Plan a logical narrative structure for a picture book appropriate for age "{age_range}", including character
    development, plot points, and page-by-page story progression. Ensure the story length and complexity
    align with the target age group's attention span and comprehension level.

    Note: One page consists of a core vocabulary word, one English sentence (suitable for a picture book), and its translation. (one-to-one)
  expected_output: >
    Title of the book, character descriptions, plot points, core vocabulary words, and educational elements.

write_story_content_task:
  description: >
    Transform the story outline into engaging, age-appropriate story text for each page.
    Ensure vocabulary and sentence structure are suitable for "{age_range}", while maintaining narrative flow
    and entertainment value. Use dialogue to make the story more engaging. Each page's content should be balanced in length and complexity.
    Sometimes, involve metaphors and similes to make the story more engaging.

    Note: One page consists of a core vocabulary word, one English sentence (suitable for a picture book), and its translation. (one-to-one)
  expected_output: >
    A list of story text for a complete picture book (each must contain its core vocabulary word) and core vocabulary word broken down by pages, with age-appropriate language, engaging narrative,
    and consistent pacing throughout the book.

# TODO 未来增加review
# review_content_task:
#   description: >
#     Thoroughly evaluate the story content. Assess:
#     - Age-appropriateness for "{age_range}"
#     - Educational value and accuracy
#     - Language level and clarity
#     - Story engagement and pacing
#     - Cultural sensitivity
    
#     Provide a detailed review with:
#     1. Overall quality score (1-10)
#     2. Specific issues identified
#     3. Actionable improvement suggestions
#   expected_output: >
#     Comprehensive review report including quality score, identified issues, and specific recommendations
#     for enhancing the content's effectiveness while maintaining entertainment value.

design_art_direction_task:
  description: >
    Develop comprehensive visual style guidelines for the book's illustrations based on the
    content and target age group "{age_range}". Create detailed visual style guidelines for character design, color palette, and overall artistic direction.
  expected_output: >
    Character design specifications, color palette, visual style guidelines.

create_illustrations_task:
  description: >
    You will use AI image generation tools to create illustrations for each page of a picture book following the art direction
    guidelines and content. Generate illustration prompts with multiple variations for each scene to ensure the best
    possible visual representation. Ensure illustrations are engaging and appropriate
    for "{age_range}".

    Each prompt should contain detailed consistent character design, detailed scene description, and storyboard instructions of the elements in the scene.
    Ensure each illustration has a prominent subject that a parent can point to and explain to their child.

    Note: One illustration for one page (one-to-one)
  expected_output: >
    High-quality AI illustration prompts (e.g. for Midjourney) for each page that align with the character design, art direction, content,
    and age-appropriate visual complexity.

generate_illustrations_task:
  description: >
    Generate actual illustrations using AI image generation tools based on the prompts created.
    Ensure all images are generated at a consistent resolution of 720x1280 pixels or lower to maintain
    quality while optimizing file size. Save each generated image and track the file paths.

    Note: One illustration for one page (one-to-one)
  expected_output: >
    List of file paths to the generated illustrations, with each path corresponding to a specific
    page in sequential order. Also output the image size.

translate_content_task:
  description: >
    Translate the text into the target language "{target_language}", maintaining the
    story's charm, cultural nuances, and age-appropriate tone. Ensure the translation fits well
    with the illustrations and maintains proper pacing for each page.

    Each page consists of a core vocabulary word,one illustration, one English sentence (suitable for a picture book), and its translation.
  expected_output: >
    A list of complete translated text (each must still contain its core vocabulary word) & core vocabulary word for each page in "{target_language}", preserving the original story's
    engagement level and educational value while being culturally appropriate.

generate_html_pages_task:
  description: >
    Generate a single-page industrial-level children's picture book HTML template that combine text content, translations, and illustrations into a cohesive layout
    suitable for A4 paper printing. Make sure the template has:
      - Illustration (720x1280, make sure the image covers the entire page!)
      - English text content with core vocabulary word highlighted (case-insensitive)
      - Translated text content with core vocabulary word highlighted (case-insensitive)

    Ensure professional publication-quality aesthetics with:
    - Proper spacing and alignment
    - Proper visual hierarchy; the text should be readable and the image should be the main focus
    - Age-appropriate design elements and decorations for "{age_range}"
  expected_output: >
    An industrial-level children's picture book jinja2 html template (with beautiful UI CSS and necessary JS) with the following keys {{ illustration_path }}  {{ english_text }}   {{ translated_text }}   {{ english_highlight_vocabulary_word }}  {{ translated_highlight_vocabulary_word }}
    Directly output a complete, standalone HTML file (in string) that can be opened in any browser. No extra text or comments. The template should include all necessary HTML structure, fancy CSS styling, and JavaScript functionality.